name: Android ARM64 Builder

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.25.2
  LLVM_VERSION: 15.0.6
  NDK_VERSION: r25b

jobs:
  delete_latest_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: delete latest release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  android_arm64:
    runs-on: ubuntu-latest
    needs: delete_latest_release
    permissions:
      contents: write
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: init linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile android arm64
      run: |
        # Menggunakan --arch=arm64 khusus untuk HP Android 64-bit modern
        python3 scripts/platform_builder.py --platform=android --arch=arm64 --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android
        tar -zcvf build/dobby-android-arm64.tar.gz build/android
        cp build/dobby-android-arm64.tar.gz artifact/
      shell: bash

    - name: print output
      run: |
        ls -lha .

    - name: update release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        body: "Dobby build otomatis khusus Android ARM64 (64-bit)"
        artifacts: "build/dobby-android-arm64.tar.gz"
        allowUpdates: true
        replacesArtifacts: true
